client_data_column_filter = ['securities_symbol',
                             'price',
                             'securities_authorizedShares',
                             'securities_authorizedSharesAsOfDate',
                             'securities_unlimitedAuthorizedShares',
                             'securities_outstandingShares',
                             'securities_outstandingSharesAsOfDate',
                             'securities_unrestrictedShares',
                             'securities_unrestrictedSharesAsOfDate',
                             'securities_publicFloat',
                             'securities_publicFloatAsOfDate',
                             'securities_tierDisplayName',
                             'securities_tierStartDate',
                             'securities_isCaveatEmptor',
                             'securities_shortInterest',
                             'securities_shortInterestDate',
                             'securities_transferAgents_name',
                             'securities_transferAgents_website',
                             'securities_transferAgents_email',
                             'spac',
                             'website',
                             'email',
                             'linkedin',
                             'twitter',
                             'facebook',
                             'address1',
                             'phone',
                             'businessDesc',
                             'isAlternativeReporting',
                             'hasLatestFiling',
                             'officers_name']


client_data_columns_cleaned = ['Symbol',
                              'Price',
                              'Authorized Shares',
                              'Authorized Shares Date',
                              'Unlimited Authorized Shares',
                              'Outstanding Shares',
                              'Outstanding Shares Date',
                              'Unrestricted Shares',
                              'Unrestricted Shares Date',
                              'Float',
                              'Float Date',
                              'Tier',
                              'Tier Start Date',
                              'Caveat Emptor',
                              'Short Interest',
                              'Short Interest Date',
                              'Transfer Agent',
                              'Transfer Agent Website',
                              'Transfer Agent Email',
                              'Spac',
                              'Website',
                              'Email',
                              'LinkedIn',
                              'Twitter',
                              'Facebook',
                              'Address',
                              'Phone Number',
                              'Business Description',
                              'Alternative Reporting',
                              'Has Latest Filing',
                              'Officer Name']
